repo_url: https://github.com/shtrausslearning/shtrausslearning.github.io
repo_name: shtrausslearning.github.io
site_author: Andrey Shtrauss
site_description: Personal Website
site_name: mldsai
site_url: https://shtrausslearning.github.io
docs_dir: docs

theme:
  custom_dir: docs/overrides
  language: en
  name: material
  logo: images/logo2.svg
  favicon: images/mllibs2.svg
  font:
      text: Ubuntu
      code: Roboto Mono

  logo: images/home-logo.svg
  favicon: images/home-logo.svg
    
  features:
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.sections

  custom_dir: "docs/overrides"
  palette:
  - scheme: slate
    primary: custom
    accent: custom
    
        
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - blog:
      archive_toc: true
      archive_date_format: MMMM, yyyy
      archive_url_date_format: yyyy/MM
      pagination_per_page: 10
      pagination_format: $link_first $link_previous ~2~ $link_next $link_last
      post_excerpt_separator: <!-- more -->
  - search: null
  - markdownextradata:
      data: docs/data/render_yaml/
  - tags
  - offline
  
 
extra:
    manifest: manifest.webmanifest
    analytics:
      provider: google
      property: G-R7CLKWM3LT
      feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/arrow-up-thick
            name: This page was helpful!
            data: 1
            note: Thanks for your feedback!
          - icon: material/arrow-down-thick
            name: This page could be improved!
            data: 0
            note: Thanks for your feedback!
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/shtrausslearning
      name: shtrausslearning
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle/shtraussleaning
      name: shtrausslearning
    - icon: fontawesome/brands/telegram
      link: https://t.me/mldsai_info
      name: mldsai-info

copyright: |
  Copyright &copy; 2023-2025 <a href="https://github.com/shtrausslearning"  target="_blank" rel="noopener">Andrey Shtrauss</a>

extra_css:
  - stylesheets/customize.css
  - stylesheets/extra.css
  - stylesheets/simpleicons.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

nav:
  - <b>Home</b>: index.md
  - <b>Featured</b>: index.html#featured_work
  - <b>Latest</b>: index.html#portfolio
  - <b>Blog</b>: 
    - Blog: blog/index.md
