
# Set up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
site_name: Andrey Shtrauss
site_url: https://shtrausslearning.github.io/
repo_name: 'shtrausslearning.github.io'
repo_url: https://github.com/shtrausslearning/shtrausslearning.github.io
edit_uri: tree/master/docs/src/markdown
site_description: A Collection of Useful Snippets on Machine Learning related topics
docs_dir: markdown

##################################################################

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

##################################################################

theme:
    name: material
    icon:
        logo: fontawesome/solid/code 
        repo: fontawesome/brands/github
    language: en
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - navigation.expand
        - navigation.tracking
        - navigation.tabs
        - navigation.footer
        - navigation.indexes
        - content.tabs.link
        - content.tooltips
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow

    custom_dir: material/overrides
    palette:
      - scheme: slate
        primary: black
        accent: indigo
          
    font:
        text: Ubuntu

extra:
    manifest: manifest.webmanifest
    analytics:
      provider: google
      property: G-R7CLKWM3LT
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/shtrausslearning
      name: shtrausslearning
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle/shtraussleaning
      name: shtrausslearning
    - icon: fontawesome/brands/telegram
      link: https://t.me/mldsai_info
      name: mldsai-info

plugins:
    - blog:
        blog_toc: true
        post_excerpt: optional
        post_excerpt_separator: <!-- more -->
        archive_name: Archive
        post_slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
    - search
    - tags
    - offline

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css

copyright: |
  Copyright &copy; 2023 <a href="https://github.com/shtrausslearning"  target="_blank" rel="noopener">Andrey Shtrauss</a>

nav:
- Home: index.md

- Data Science: 

    - General: portfolio/projects.md
    - NLP: portfolio/nlp.md
    - Business: portfolio/business.md
    - Finance: portfolio/financial.md
    - Physics: portfolio/physics.md
    - Biology: portfolio/biology.md
    - Health: portfolio/health.md
    - Geospatial: portfolio/geospatial.md

- Bioinformatics: bio-portfolio.md

- mllibs:

    - About: mllibs/about.md
    - Installation: mllibs/install.md
    - Projects:
        - ML Project Phases: mllibs/projects/mlproject.md
        - ML Projects List: 
            - Gene Family Classification: mllibs/projects/gene_classification.md

    - Modules: 
        - Available modules: mllibs/modules/list.md
        - Adding new modules: mllibs/modules/adding.md
        - Grouping modules: mllibs/modules/grouping.md

    - Documentation: 
        - iterative: mllibs/documentation/iterative.md
        - storage: mllibs/documentation/data_storage.md
        - nlpm: mllibs/documentation/nlpm.md
        - nlpi: mllibs/documentation/nlpi.md
        - eda:
            - eda_simple: mllibs/documentation/eda/meda_simple.md
            - eda_splot: mllibs/documentation/eda/meda_splot.md 
            - eda_scplot: mllibs/documentation/eda/meda_scplot.md

    - Group:
        - Tasks:
          - Recommendation: mllibs/group/tasks/recom.md
          - Label Classification: mllibs/group/tasks/label_classifier.md
        - Task Status: mllibs/group/status.md
        - Meetings: mllibs/group/meetups.md
        - Members: mllibs/group/members.md

- Articles:
    - blog/index.md

- About: about.md
