# Set up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
site_name: Andrey Shtrauss
site_url: https://github.com/gmihaila/shtrausslearning.github.io
repo_name: 'shtrausslearning.github.io'
repo_url: https://github.com/shtrausslearning/shtrausslearning.github.io
edit_uri: tree/master/docs/src/markdown
site_description: A Collection of Useful Snippets on Machine Learning related topics
docs_dir: markdown

theme:
    name: material
    icon:
        logo: fontawesome/solid/code 
        repo: fontawesome/brands/github
    language: en
    features:
        # Navigation settings
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        # - navigation.tabs.sticky kikapcsolva, így kisebb a fejléc.
        - navigation.top

    custom_dir: material/overrides
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono

extra:
    manifest: manifest.webmanifest
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/shtrausslearning
      name: shtrausslearning
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle/shtraussleaning
      name: shtrausslearning
    - icon: fontawesome/brands/telegram
      link: https://t.me/mldsai_info
      name: mldsai-info

plugins:
    - blog:
    - search:
        separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra_css:
  - stylesheets/custom.css

nav:

    - home: index.md

    - collections: 
        - Data Science: ds-portfolio.md

    - mllibs:
        - introduction: mllibs/home.md
        - meetups: mllibs/meetups.md

    - blog:
        - blog/index.md
